#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 JVM_DIRECTORY"
  exit 1
fi
if ! [ -e "$1" ]; then
  echo "$1 not found"
  exit 1
fi
if ! [ -d "$1" ]; then
  echo "$1 not a directory"
  exit 1
fi
if ! [ -d "$1/bin" ]; then
  echo "$1 is not a correct JVM directory"
  exit 1
fi

for f in $1/bin/*; do
  name=`basename $f`;
    if [ ! -f "/usr/bin/$name" -o -L "/usr/bin/$name" ]; then  #some files, like jvisualvm might not be links
      echo "Updating alternative $name"
      update-alternatives --install /usr/bin/$name $name ${1%/}/bin/$name 1
      #update-alternatives --remove $name $1/bin/$name
    fi
done
